### ISSUE TITLE
Implement "yogaya generate" command for Terraform code generation

### ISSUE THREAD

**Issue by yogaya-taka** [Yogaya-Inc/yogaya-cli#3]
Develop functionality to generate Terraform configurations from existing cloud resources.

Key Implementation Points:
- Integrate Former2 for AWS resource scanning
- Implement or integrate solution for GCP resource scanning
- Implement or integrate solution for Azure resource scanning
- Generate consolidated Terraform code
- Handle multiple cloud providers and accounts

Technical Requirements:
- Research and integrate Former2 codebase
- Identify/develop solutions for GCP/Azure
- Implement resource scanning logic
- Generate valid Terraform configurations
- Handle state management

Acceptance Criteria:
- Successfully scans resources from all configured cloud providers
- Generates valid Terraform code
- Handles errors gracefully
- Provides progress feedback during generation
- Documentation for generation process

Dependencies: Requires completion of #2

**Comment by vradars** [comment]
@yogaya-taka let's build yogaya cli as a fork from terraformer project. https://github.com/Yogaya-Inc/yogaya_cli is the fork I recently created.
